=== hectorbh78/Trabajo-Intermodular/PuchamonGris/Lenguaje/esquema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">

    <!-- Elemento raíz -->
    <xs:element name="puchadex">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="entrenador" type="EntrenadorType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- ENTRENADOR -->
    <xs:complexType name="EntrenadorType">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="puchamones">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="puchamon" type="PuchamonType" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="inventario">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="objeto" type="ObjetoType" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <!-- PUCHAMON -->
    <xs:complexType name="PuchamonType">
        <xs:sequence>
            <xs:element name="idPuch" type="xs:int"/>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="nivel" type="xs:int"/>
            <xs:element name="vida" type="xs:int"/>
            <xs:element name="idEntrenador" type="xs:int"/>
            <xs:element name="tipos">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="tipo" type="xs:string" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="ataques">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ataqueNormal" type="AtaqueType" maxOccurs="unbounded"/>
                        <xs:element name="ataqueEspecial" type="AtaqueType" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <!-- ATAQUE -->
    <xs:complexType name="AtaqueType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="danio" type="xs:int" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- OBJETO -->
    <xs:complexType name="ObjetoType">
        <xs:sequence>
            <xs:element name="idEntrenador" type="xs:int"/>
            <xs:element name="idObjeto" type="xs:int"/>
        </xs:sequence>
      
        <xs:attribute name="id" type="xs:ID" use="required"/>
       
    </xs:complexType>

</xs:schema>

=== hectorbh78/Trabajo-Intermodular/PuchamonGris/Lenguaje/datos.xml
<?xml version="1.0" encoding="UTF-8"?>
<puchadex xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="esquema.xsd">
    <entrenador id="1">
        <nombre>Ruben</nombre>
        <puchamones>
            <puchamon id="P001">
                <nombre>Lagasur</nombre>
                <nivel>10</nivel>
                <vida>35</vida>
                <tipos>
                    <tipo>Planta</tipo>
                </tipos>
                <ataques>
                    <ataque daño="50">Coletazo</ataque>
                </ataques>
            </puchamon>
            <puchamon id="P002">
                <nombre>Salasaur</nombre>
                <nivel>21</nivel>
                <vida>65</vida>
                <tipos>
                    <tipo>Planta</tipo>
                    <tipo>Veneno</tipo>
                </tipos>
            </puchamon>
        </puchamones>
        <inventario>
            <objeto id="OBJ1">
                <nombre>Pocion</nombre>
                <efecto>Cura 20 HP</efecto>
            </objeto>
            <objeto id="OBJ2">
                <nombre>SuperPocion</nombre>
                <efecto>Cura 50 HP</efecto>
            </objeto>
        </inventario>
    </entrenador>
    
    <entrenador id="2">
        <nombre>Jp</nombre>
        <puchamones>
            <puchamon id="P004">
                <nombre>Jai</nombre>
                <nivel>12</nivel>
                <vida>40</vida>
                <tipos>
                    <tipo>Acero</tipo>
                </tipos>
            </puchamon>
        </puchamones>
        <inventario>
            <objeto id="OBJ1">
                <nombre>Pocion</nombre>
                <efecto>Cura 20 HP</efecto>
            </objeto>
        </inventario>
    </entrenador>
</puchadex>
